Stability improvements and bug fixes
SouthAlbertaAI/CrossJoin-AESO pull request #10
Opened 2024-12-01 02:45 UTC by SouthAlbertaAI

This includes some bug fixes and the early pieces of the future alert mode and 511 alberta road conditions commands

I'll continue to take care of the alert mode and road conditions pieces as I have a specific view for them even though they are committed in a skeleton state for now.

Expect a PR for the alert and road conditions parts soon!

In addition: You will see a pre commit yaml file. This is for future implementation but I use its checks in my current environment to format code before its commit. This can be configured to run automatically using the pre-commit library

2024-12-01 02:50 UTC, glob-bruh commented
Will check tonight.

2024-12-01 02:52 UTC, SouthAlbertaAI commented
Sounds good, just updated PR to remove some old breakpoint bug testing code

2024-12-01 04:11 UTC, glob-bruh requested changes
The 511 API call should have the optional parameters included.



> https://511.alberta.ca/api/v2/get/winterroads
> should be
> https://511.alberta.ca/api/v2/get/winterroads?format=json&lang=en

If you dont want to change this then it can be pushed through.

2024-12-01 04:11 UTC, glob-bruh commented on static/CrossJoin_CommandLogic.py
> +        "https://511.alberta.ca/api/v2/get/winterroads",
`https://511.alberta.ca/api/v2/get/winterroads`
should be 
`https://511.alberta.ca/api/v2/get/winterroads?format=json&lang=en`

2024-12-02 02:27 UTC, SouthAlbertaAI commented
There we go changes are all made

2024-12-02 02:28 UTC, glob-bruh approved these changes

2024-12-02 02:29 UTC, merged